upgrade to C++17 for compatibility with Eigen 3.40.90
ros/robot_state_publisher pull request #208
Opened 2023-10-06 19:10 UTC by daizhirui

With Eigen 3.40.90 installed from source, we need to change the C++ standard from 11 to 17. Otherwise, we get error: `#error This compiler appears to be too old to be supported by Eigen`.

2023-10-06 19:14 UTC, daizhirui commented
The CI seems to be broken: `KeyError: 'ros-noetic-catkin'`.

2023-10-30 16:58 UTC, sloretz requested changes
Thanks for the PR!

[Noetic targets C++ 14](https://www.ros.org/reps/rep-0003.html#noetic-ninjemys-may-2020-may-2025) , and ROS Noetic [is the last supported ROS 1 release](https://www.openrobotics.org/blog/2020/5/23/noetic-ninjemys-the-last-official-ros-1-release).

I can keep this open if you'd be willing to make it c++14 instead, but otherwise I'll close it.

2023-10-30 16:58 UTC, sloretz commented on CMakeLists.txt
> +    add_compile_options(/std:c++17)
Ah, I'd recommend replacing this logic with `target_compile_features(target_name PUBLIC cxx_std_14)`. Here's an example from ROS 2: https://github.com/ros2/rclcpp/blob/fcbe64cff4bea3109531254ceb2955dc4b1bb320/rclcpp/CMakeLists.txt#L196

2023-10-30 18:15 UTC, daizhirui commented on CMakeLists.txt
> +    add_compile_options(/std:c++17)
I change it as you suggested.

2023-10-30 18:15 UTC, daizhirui commented
Changed to C++14 and tested with Eigen 3.4.90

2023-10-30 18:20 UTC, sloretz approved these changes
Thanks for iterating!

2023-10-30 18:20 UTC, merged