Make rostest dependency conditional, depending on CATKIN_ENABLE_TESTING
ros/robot_state_publisher pull request #66
Opened 2016-11-02 12:52 UTC by jvgomez

Closes #58

2016-11-02 18:35 UTC, tfoote approved these changes
lgtm

2016-11-03 01:29 UTC, wjwwood requested changes
One small change, otherwise, lgtm.

2016-11-03 01:29 UTC, wjwwood commented on CMakeLists.txt
> +  find_package(rostest)
Please use `REQUIRED`.

2016-11-09 11:21 UTC, jvgomez commented
@wjwwood I have done the requested changes.

2016-11-16 18:54 UTC, wjwwood approved these changes

2016-11-16 18:54 UTC, merged